config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions
  get '/admins', to:'admins#index'
  resources :admins
  #get '/authors', to: 'authors#index'
  #get '/authors/new', to: 'authors#new'
  #delete '/authors/:id', to: 'authors#destroy'
 #get '/authors/:author_id/books/new', to: 'books#new'
  #get '/authors/:author_id/books/:id/edit', to: 'books#edit'
 #resources :books
 resources :authors
 get "/books", to: "books#index"
 resources :authors, only: [:new,:create, :edit, :update, :destroy, :show] do 
   resources :books 
 end
 # resources :authors, only: [:index, :new, :create, :show, :destroy] do
 #   resources:books 
 # end
  get '/lib',to:'authors#literature'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "users#new"
   
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
</div>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<%= form_with(model:@admin,local: true) do |form| %>
  <h2>Admin Login</h2>
  <div>
    <%= form.label :Email %><br>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :Password %><br>
    <%= form.text_field :password_digest%>
  </div>
  
  <div>
    <%= form.submit "Login" %>
  </div>
<% end %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>
<h3>Welcome Admin</h3>
<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>