config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions
  get '/admins', to:'admins#index'
  resources :admins
  #get '/authors', to: 'authors#index'
  #get '/authors/new', to: 'authors#new'
  #delete '/authors/:id', to: 'authors#destroy'
 #get '/authors/:author_id/books/new', to: 'books#new'
  #get '/authors/:author_id/books/:id/edit', to: 'books#edit'
 #resources :books
 resources :authors
 get "/books", to: "books#index"
 resources :authors, only: [:new,:create, :edit, :update, :destroy, :show] do 
   resources :books 
 end
 # resources :authors, only: [:index, :new, :create, :show, :destroy] do
 #   resources:books 
 # end
  get '/lib',to:'authors#literature'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "users#new"
   
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books

    def self.search(search)
        if search
            author_type = Author.find_by(name:search)
            if author_type
                self.where(id: author_type)
            else
                @authors = Author.all
            end
        else
            @authors = Author.all
        end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    #@authors = Author.all
    @authors = Author.search(params[:search])
    p @authors
  end

  def new
    @author = Author.new()
  end

  def Literature
    render "literature"
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to authors_path
    else
      render "new"
    end
  end
  
  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      flash[:notice] = "Edited"
      redirect_to authors_path
    else
      render "edit"
    end
  end

  def show
    @author=Author.find(params[:id])
    @books = @author.books
   
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:name,:country,:awards,:search)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<h1>Edit Authors</h1>
</br>
<%= form_with(model:@author,local: true) do |form| %>
  <div>
    <%= form.label :Author_name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :Country%><br>
    <%= form.text_field :country%>
  </div>
  <div>
    <%= form.label :Awards%><br>
    <%= form.text_field :awards%>
  </div>
  </br>
  <div>
    <%= form.submit "Create" %>
  </div>
<% end %>

app/views/authors/form.html.erb
<%= form_with(modal: @author) do |f| %>
<label for="exampleDataList" class="form-label">Authors</label>
<input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Type to search...">
<datalist id="datalistOptions">
  <option value="Kalki">
  <option value="RK">
  <option value="Indra">
  <option value="Agastha Christie">
  <option value="Jeyakanthan">
</datalist>
<% end %>

app/views/authors/index.html.erb
<%c=0%>
<h1>Authors</h1>
<%= form_tag authors_path, :method =>"get" do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag("Search", :name =>nil)%>
  <% end %>
<%= link_to "New",new_author_path %>
<table class="table table-secondary">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Author ID</th>
      <th scope="col">Name</th>
      <th scope="col">Country</th>
      <th scope="col">Awards</th>
      <th scope="col">Books</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
      <%c=c+1%>
      <td><%=c%></td>
      <td><%=author.id %></td>
      <td><%=author.name %></td>
      <td><%=author.country %></td>
      <td><%=author.awards %></td>
      <td><%= link_to "books",author_path(author) %></td>
      <td><%=link_to "Edit",edit_author_path(author)%></td>
      <td><%=button_to 'delete',author_path(author), method: :delete %></td>
      </tr>
      <% end %>
    
  </tbody>
</table>

app/views/authors/literature.html.erb
<!DOCTYPE html>
<html></br>
<head>
<h1 class="lit">Lingering Literature - A Guide</h1>
<style>

.lit{
    font-size:30px;
    font-style:oblique;
    text-align:center;
    
}
.book{
    font-size:20px;
    font-style:oblique;
    text-align:center;
}
body{
    background-image:url('/assets/light.jpg');
    background-repeat:no-repeat;
    background-position:center;
    background-size:cover;
}

</style>
</head>
<body>
<p>Literature, a body of written works. The name has traditionally been applied to those imaginative works of poetry and prose distinguished by the intentions of their authors and the perceived aesthetic excellence of their execution. Literature may be classified according to a variety of systems, including <b>language</b>, <b>national origin</b>, <b>historical period</b>, <b>genre</b>, and <b>subject matter</b>.</p>
<p>Books play a quintessential role in every student's life by introducing them to a <b>world of imagination</b>, providing knowledge of the outside world, improving their reading, writing and speaking skills as well as boosting memory and intelligence.They are the only gateway, a sort of <b>time-machine</b> that would take the reader to the past and the future </p>
<p><b>Authors</b> on the other hand, inject their knowledge,experience and perspective, basically the essentials needed for a work to turn lively and enthralling! </p>
<p>Books just don't fit into the two types of <b>fiction</b> and <b>non-fiction</b>. They diversify into multiple sub-types depending on the genre</p>
<p><b>"Fiction"</b> refers to literature created from <b>imagination</b>. Mysteries, science fiction, romance, fantasy, chick lit, crime thrillers are all fiction genres.</p>
<p><b>"Non-fiction"</b> refers to literature based on <b>facts</b>. It is the broadest category of literature. The Non-fiction Department has books in many categories including biography, business, cooking, health and fitness, pets, crafts, home decorating, languages, travel, home improvement, religion, art and music, history, self-help, true crime, science and humor.</p>
<p>Here is a website dedicated solely to the world of authors and their books. It provides the viewer the information on some of the notable authors around the world and their contributions to the literary world in the form of books</p>
<h3 class="book">Happy reading!</h3>
<div class="col-md-16 text-center">
<%=button_to "Let's go", authors_path, method: :get%>
</div>
</body>
</html>

app/views/authors/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.author{
    text-align:center;
    background:url('/assets/author.jpg');
    background-size:cover;
    background-repeat:no-repeat;
}
</style>
</head>
<body>
<%= form_with(model:@author,local: true) do |form| %>
  <h2>Author</h2>
  <div>
    <%= form.label :Author_name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :Country%><br>
    <%= form.text_field :country%>
  </div>
  <div>
    <%= form.label :Awards%><br>
    <%= form.text_field :awards%>
  </div>
  </br>
  <div>
    <%= form.submit "Create" %>
  </div>
<% end %>




<!-- 
# </br>
# <div>
#   <label for="name" class="form-label">Author Name</label>
#   <input type="text" class="form-control" id="name">
# </div>
# <div>
#   <label for="book" class="form-label">Country</label>
#   <input type="text" class="form-control" id="book" >
# </div>
# <div>
#   <label for="genre" class="form-label">Awards</label>
#   <input type="text" class="form-control" id="genre">
# </div>
# </br>
# <button type="submit" class="btn btn-primary">Submit</button>
# </div>-->


</body>
</html>

app/views/authors/show.html.erb
    <h1>Books</h1>
    <%= link_to "New",new_author_book_path(@author) %>

<table class="table table-secondary">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Name</th>
      <th scope="col">Content</th>
      <th scope="col">Genre</th>
      <th scope="col">Published</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>

    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
      <td><%= book.id %></td>
      <td><%=book.name %></td>
      <td><%=book.content %></td>
      <td><%=book.genre %></td>
      <td><%=book.published %></td>
      <td><%=link_to "Edit", edit_author_book_path(@author, book)%></td>
      <td><%=button_to "Delete",author_book_path(@author, book), method: :delete%></td>
      </tr>
      <% end %>
</tbody>
</table>
      