config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :sessions
  get '/admins', to:'admins#index'
  resources :admins
  #get '/authors', to: 'authors#index'
  #get '/authors/new', to: 'authors#new'
  #delete '/authors/:id', to: 'authors#destroy'
 #get '/authors/:author_id/books/new', to: 'books#new'
  #get '/authors/:author_id/books/:id/edit', to: 'books#edit'
 #resources :books
 resources :authors
 get "/books", to: "books#index"
 resources :authors, only: [:new,:create, :edit, :update, :destroy, :show] do 
   resources :books 
 end
 # resources :authors, only: [:index, :new, :create, :show, :destroy] do
 #   resources:books 
 # end
  get '/lib',to:'authors#literature'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "users#new"
   
end

app/views/common/_navbar.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <!--<a class="navbar-brand" href="#">Literature</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="/">Literature</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= books_path %>">Books</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="<%= authors_path %>">Authors</a>
      </li>
      <!--<li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      
        <!--<li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>-->
      </ul>
      <!--<form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
    </div>
  </div>
</nav>
</div>